#ifndef VCDIFF_STATE_H
#define VCDIFF_STATE_H

#include "vcdiff.h"

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

#define FOREACH_STATE_HDR(STATE) \
	STATE(STATE_HDR_MAGIC0) \
	STATE(STATE_HDR_MAGIC1) \
	STATE(STATE_HDR_MAGIC2) \
	STATE(STATE_HDR_MAGIC3) \
	STATE(STATE_HDR_INDICATOR)

#define FOREACH_STATE_WIN_HDR(STATE) \
	STATE(STATE_WIN_HDR_INDICATOR) \
	STATE(STATE_WIN_HDR_SEGMENT_LEN) \
	STATE(STATE_WIN_HDR_SEGMENT_POS) \
	STATE(STATE_WIN_HDR_DELTA_LEN) \
	STATE(STATE_WIN_HDR_WINDOW_LENGTH) \
	STATE(STATE_WIN_HDR_DELTA_INDICATOR) \
	STATE(STATE_WIN_HDR_DATA_LEN) \
	STATE(STATE_WIN_HDR_INST_LEN) \
	STATE(STATE_WIN_HDR_ADDR_LEN)

#define FOREACH_STATE_WIN_BODY(STATE) \
	STATE(STATE_WIN_BODY_INST)

enum {
	STATE_HDR = 0x0000,
	STATE_WIN_HDR = 0x0100,
	STATE_WIN_BODY = 0x0200,
	STATE_FINISH = 0xff00
};

enum {
	FOREACH_STATE_HDR(GENERATE_ENUM)
};

enum {
	FOREACH_STATE_WIN_HDR(GENERATE_ENUM)
};

enum {
	FOREACH_STATE_WIN_BODY(GENERATE_ENUM)
};

const char *vcdiff_state_str (vcdiff_t *ctx);

const char *vcdiff_error_str (vcdiff_t *ctx);

#endif
